### ISSUE TITLE
Sql Mistake

### ISSUE THREAD

**Issue by Sina30** [Sander2222/admin_menu#1]
I have it in there now and it works    ADD bantime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

Mistake
SQL command: copy

ALTER TABLE users
ADD bantime TIMESTAMP DEFAULT ZERO,
ADD banreason VARCHAR(500);
MySQL reports: Documentation

#1067 - Incorrect default value (DEFAULT) for 'bantime'

**Comment by KEKHUBCypherWalls** [comment]
Please try this!:
https://pastebin.com/17CCu0r6

**Comment by Sander2222** [comment]
hey yea thanks for the issue i gonna fix it now
